name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js and pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run docs:build
      - name: Configure Pages
        uses: actions/configure-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          cname: ${{ secrets.CNAME }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.0
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: docs/.vitepress/dist
          cname: ${{ secrets.CNAME }}
